[package]
name = "crtcli"
description = "Command-line tool for interacting with Creatio and Creatio packages"
version = "0.3.0"
edition = "2024"
authors = ["heabijay <heabijay@gmail.com>"]
repository = "https://github.com/heabijay/crtcli"
license = "MIT"

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.13"
async-trait = "0.1.89"
crossterm = { version = "0.29.0", features = ["event-stream"] }
clap_complete = "4.5.66"
dotenvy = "0.15.7"
flate2 = "1.1.9"
futures = "0.3.32"
hyper-util = "0.1.20"
indexmap = { version =  "2.13.0", features = ["serde"] }
indicatif = "0.18.4"
quick-xml = "0.39.2"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["macros", "io-std"] }
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
tokio-util = { version = "0.7.18", features = ["io", "io-util"] }
toml = "1.0.3"
urlencoding = "2.1.3"
walkdir = "2.5.0"
zip = "8.1.0"
rkyv = "0.8.15"

[dependencies.clap]
version = "4.5.60"
features = ["derive", "env", "suggestions", "usage"]

[dependencies.hyper-rustls]
version = "0.27.7"
default-features = false
features = [
    "http1",
    "http2",
    "logging",
    "ring",
    "tls12",
]

[dependencies.reqwest]
version = "0.13.2"
default-features = false
features = [
    "charset",
    "http2",
    "form", 
    "json",
    "multipart", 
    "rustls-no-provider",
    "stream",
    "system-proxy",
    "query",
]

[dependencies.rustls]
version = "0.23.36"
default-features = false
features = [
    "std",
    "ring",
    "logging",
    "tls12",
]

[dependencies.time]
version = "0.3.47"
features = ["formatting", "local-offset", "macros"]

[dev-dependencies]
pretty_assertions = "1.4.1"
