[workspace]
resolver = "2"
members = ["src/crtcli"]

[profile.dev]
debug = false # Disable debug symbols to speedup dev compilation

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 3