use std::env::current_exe;
use std::process::Command;
use clap::Args;
use thiserror::Error;
use crate::cmd::cli::{CliCommand, CommandResult};

#[derive(Debug, Args)]
pub struct AutogenCommand {
    
}

#[derive(Error, Debug)]
enum AutogenCommandError {
    
}

impl CliCommand for AutogenCommand {
    fn run(self) -> CommandResult {
        dbg!(current_exe()?);

        let mut path = current_exe()?;
        
        path.pop();
        path.pop();
        path.pop();
        
        path.push("src");
        path.push("crtcli.dotnet");
        path.push("bin");
        path.push("Release");
        path.push("net9.0");

        if cfg!(target_os = "windows") {
            path.push("CrtCli.Dotnet.exe");
        } else {
            path.push("CrtCli.Dotnet");
        };
        
        dbg!(&path);
        
        Command::new(path)
            .env("CRTCLI_DOTNET_CALLED_BY_CRTCLI", "true")
            .arg("generate-autogenerated-package-schemas")
            .arg("{}")
            .spawn()
            .unwrap()
            .wait()?;
        
        todo!()
    }
}