const AUTOGENERATED_FOLDER: &str = "Autogenerated";
const AUTOGENERATED_LIB_FOLDER: &str = "Lib";
const AUTOGENERATED_SRC_FOLDER: &str = "Src";

pub const ASSEMBLIES_FOLDER: &str = "Assemblies";
pub const DATA_FOLDER: &str = "Data";
pub const FILES_FOLDER: &str = "Files";
pub const RESOURCES_FOLDER: &str = "Resources";
pub const SCHEMAS_FOLDER: &str = "Schemas";
pub const SQL_SCRIPTS_FOLDER: &str = "SqlScripts";

pub const PKG_FOLDERS: [&str; 6] = [
    ASSEMBLIES_FOLDER,
    DATA_FOLDER,
    FILES_FOLDER,
    RESOURCES_FOLDER,
    SCHEMAS_FOLDER,
    SQL_SCRIPTS_FOLDER,
];

pub const PKG_DESCRIPTOR_FILE: &str = "descriptor.json";
